### ISSUE TITLE
Error in simple demonstration

### ISSUE THREAD

**Issue by fbao-fudan** [concavegit/kfda#1]
Hi there, 

Thank you for providing this tool. However, when I test the tool using simple input, I got an error:

```
cls = Kfda(kernel='rbf', n_components=2)
train_embeddings = cls.fit_transform(X, y)
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-921a6293893c> in <module>
      1 cls = Kfda(kernel='rbf', n_components=2)
----> 2 train_embeddings = cls.fit_transform(X, y)

~/opt/anaconda3/lib/python3.7/site-packages/sklearn/base.py in fit_transform(self, X, y, **fit_params)
    554         else:
    555             # fit method of arity 2 (supervised transformation)
--> 556             return self.fit(X, y, **fit_params).transform(X)
    557 
    558 

~/opt/anaconda3/lib/python3.7/site-packages/kfda/kfda.py in transform(self, X)
    115             projected onto the fisher directions.
    116         """
--> 117         check_is_fitted(self)
    118         return pairwise_kernels(
    119             X, self.X_, metric=self.kernel, **self.kwds

TypeError: check_is_fitted() missing 1 required positional argument: 'attributes'

**Comment by concavegit** [comment]
Hello fbaothu, it looks like you are using an old version of scikit-learn: https://stackoverflow.com/questions/60432260/typeerror-check-is-fitted-missing-1-required-positional-argument-attributes
